steps:
  # Step to set up Docker Buildx
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'create', '--name', 'mybuilder']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'use', 'mybuilder']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'inspect', '--bootstrap']

  # Step to authenticate to Google Cloud Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo ${_SERVICE_ACCOUNT_KEY} > /workspace/service-account-key.json
        gcloud auth activate-service-account --key-file=/workspace/service-account-key.json
        gcloud config set project $PROJECT_ID
        gcloud auth configure-docker

  # Step to build and push worker-cli image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    id: Build and push worker-cli image to GCR
    args:
      [
        'buildx', 'build', '.', 
        '--platform', 'linux/amd64,linux/arm64',
        '--tag', 'gcr.io/$PROJECT_ID/betterscan-ce-worker-cli:amd64-latest',
        '--tag', 'gcr.io/$PROJECT_ID/betterscan-ce-worker-cli:arm64-latest',
        '--tag', 'gcr.io/$PROJECT_ID/betterscan-ce-worker-cli:latest',
        '--push',
        '--file', 'docker/docker/worker-cli/Dockerfile'
      ]

images:
  - 'gcr.io/$PROJECT_ID/betterscan-ce-worker-cli:latest'

options:
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'

substitutions:
  _SERVICE_ACCOUNT_KEY: 'your-service-account-key'
