steps:
  # Step 1: Access the service account key from Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=${_SECRET_NAME} > /workspace/service-account-key.json

  # Step 2: Authenticate Docker with your PAT
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo ${_PAT} | docker login -u ${_DOCKER_USERNAME} --password-stdin https://gcr.io

  # Step 3: Set up Docker Buildx
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'create', '--name', 'mybuilder']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'use', 'mybuilder']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'inspect', '--bootstrap']

  # Step 4: Create a key for the service account
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        PROJECT_ID=$(gcloud config get-value project)
        SERVICE_ACCOUNT_EMAIL="betterscan-service@${PROJECT_ID}.iam.gserviceaccount.com"
        KEY_FILE="/workspace/my-service-account-key.json"
        gcloud iam service-accounts keys create $KEY_FILE \
          --iam-account=$SERVICE_ACCOUNT_EMAIL

  # Step 5: Save the key to a specified location (like a Cloud Storage bucket)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BUCKET_NAME=${_BUCKET_NAME}
        KEY_FILE="/workspace/my-service-account-key.json"
        gsutil cp $KEY_FILE gs://$BUCKET_NAME/

  # Optionally: Print the key file location
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Service account key saved to gs://$BUCKET_NAME/my-service-account-key.json"

  # Step 6: Authenticate to Google Cloud
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth activate-service-account --key-file=/workspace/service-account-key.json
        gcloud config set project ${PROJECT_ID}
        gcloud auth configure-docker

  # Step 7: Build and push worker-cli image to GCR with multiple tags
  - name: 'gcr.io/cloud-builders/docker'
    id: Build and push worker-cli image to GCR
    args:
      [
        'buildx', 'build', '.', 
        '--platform', 'linux/amd64,linux/arm64',
        '--tag', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:amd64-${_TAG}',
        '--tag', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:arm64-${_TAG}',
        '--tag', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${_TAG}',
        '--push',
        '--file', 'docker/docker/worker-cli/Dockerfile'
      ]

images:
  - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${_TAG}'
  - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:amd64-${_TAG}'
  - 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:arm64-${_TAG}'

options:
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'


substitutions:
  _PAT: ''
  _DOCKER_USERNAME: ''
  _IMAGE_NAME: 'betterscan-ce-worker-cli'
  _TAG: 'latest'
  _SECRET_NAME: 'my-service-account-key'
  _BUCKET_NAME: 'betterscan-ce'
  _KEYFILE: ''
