/*
 * This file is part of Betterscan CE (Community Edition).
 *
 * Betterscan is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Betterscan is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Betterscan. If not, see <https://www.gnu.org/licenses/>.
 *
 * Originally licensed under the BSD-3-Clause license with parts changed under
 * LGPL v2.1 with Commons Clause.
 * See the original LICENSE file for details.
*/
version: '3'
services:
  server:
    image: scanmycode/scanmycode3-ce:server 
    restart: always
    depends_on:
      - postgres
    working_dir: /srv/scanmycode/
    command: /bin/sh -c "python /srv/scanmycode/manage.py setup && python /srv/scanmycode/manage.py runserver"
    ports:
      - 5000:5000
    volumes:
      - server1:/srv/scanmycode/quantifiedcode/data/repositories/
      - server2:/srv/scanmycode/quantifiedcode/backend/data/tasks/

  postgres:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: qc
      POSTGRES_USER: qc
      POSTGRES_PASSWORD: qc
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  worker:
    image: scanmycode/scanmycode3-ce:worker
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - postgres
      - server
    working_dir: /srv/scanmycode/
    command: /bin/sh -c "python /srv/scanmycode/manage.py runworker"
    volumes:
      - server1:/srv/scanmycode/quantifiedcode/data/repositories/
      - server2:/srv/scanmycode/quantifiedcode/backend/data/tasks/

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=qc
      - RABBITMQ_DEFAULT_PASS=qc
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  db-data:
  server1:
  server2:
