# 
# This file is part of Betterscan CE (Community Edition).
#
# Betterscan is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Betterscan is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Betterscan. If not, see <https://www.gnu.org/licenses/>.
#
# Originally licensed under the BSD-3-Clause license with parts changed under
# LGPL v2.1 with Commons Clause.
# See the original LICENSE file for details.
#

version: '3'
services:
  server:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    restart: always
    depends_on:
      - postgres
    working_dir: /srv/betterscan-ce/
    entrypoint: sh
    command: -c "mkdir -p data1/repositories; mkdir -p data2/tasks; mkdir -p setup_state; if [ -f /srv/betterscan-ce/setup_state/setup_done ]; then curl --silent --output /dev/null https://dl.betterscan.io/run-docker.html; python3.8 /srv/betterscan-ce/manage.py runserver; else python3.8 /srv/betterscan-ce/manage.py setup  && touch /srv/betterscan-ce/setup_state/setup_done; fi"

    ports:
      - 5000:5000
    volumes:
      - ./data1:/srv/betterscan-ce/quantifiedcode/data/
      - ./data2:/srv/betterscan-ce/quantifiedcode/backend/data/tasks
      - ./setup_state:/srv/betterscan-ce/setup_state
    links:
      - "postgres"

  postgres:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: qc
      POSTGRES_USER: qc
      POSTGRES_PASSWORD: qc
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  worker_1:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    ulimits:
      stack: -1
    hostname: worker_1
    restart: on-failure
    depends_on:
      - rabbitmq3
      - postgres
      - server
    working_dir: /srv/betterscan-ce/
    entrypoint: sh
    command: -c "python3.8 /srv/betterscan-ce/manage.py runworker"
    volumes:
      - ./data1:/srv/betterscan-ce/quantifiedcode/data/
      - ./data2:/srv/betterscan-ce/quantifiedcode/backend/data/tasks
    links:
      - "rabbitmq3"
      - "server"
      - "postgres"  

  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=qc
      - RABBITMQ_DEFAULT_PASS=qc
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

volumes:
  db-data:
    driver: local

