name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend, worker, worker-cli]
        include:
          - service: backend
            dockerfile: docker/docker/backend/Dockerfile
            context: docker/docker/backend
            component: backend
          - service: worker
            dockerfile: docker/docker/worker/Dockerfile
            context: docker/docker/worker
            component: worker
          - service: worker-cli
            dockerfile: docker/docker/worker-cli/Dockerfile
            context: docker/docker/worker-cli
            component: worker-cli
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: auth
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2


      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            tcosolutions/betterscan-{{ matrix.component }}:latest
            tcosolutions/betterscan-{{ matrix.component }}:${{ github.sha }}

          ssh: |
            default=${{ env.SSH_AUTH_SOCK }}
