name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [worker-cli]
        include:
          - service: server
            dockerfile: docker/docker/backend/Dockerfile
            context: docker/docker/backend
            component: server
          - service: worker
            dockerfile: docker/docker/worker/Dockerfile
            context: docker/docker/worker
            component: worker
          - service: worker-cli
            dockerfile: docker/docker/worker-cli/Dockerfile
            context: docker/docker/worker-cli
            component: worker-cli
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    
      - name: Checkout code
        uses: actions/checkout@v3
      - name: auth
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/betterscan-${{ matrix.component }}:latest
            ghcr.io/${{ github.repository_owner }}/betterscan-${{ matrix.component }}:${{ github.sha }}
          ssh: |
            default=${{ env.SSH_AUTH_SOCK }}
