name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [worker-cli]
        include:
          - service: worker-cli
            dockerfile: docker/docker/worker-cli/Dockerfile
            context: docker/docker/worker-cli
            component: worker-cli
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5
      
      - name: Authenticate SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2.1.3
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/betterscan-ce/betterscan-${{ matrix.component }}:latest -t gcr.io/betterscan-ce/betterscan-${{ matrix.component }}:${{ github.sha }} -f ${{ matrix.dockerfile }} ${{ matrix.context }}

      - name: Push Docker image
        run: |
          docker push gcr.io/betterscan-ce/betterscan-${{ matrix.component }}:latest
          docker push gcr.io/betterscan/betterscan-${{ matrix.component }}:${{ github.sha }}
