name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [server,worker]
        include:
          - service: server
            dockerfile: docker/docker/server/Dockerfile
            context: docker/docker/server
            component: server
          - service: worker
            dockerfile: docker/docker/worker/Dockerfile
            context: docker/docker/worker
            component: worker
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64
          push: true
          tags: |
            sunsolution/betterscan-${{ matrix.component }}:latest
            sunsolution/betterscan-${{ matrix.component }}:${{ github.sha }}
 
