name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [worker-cli]
        include:
          - service: worker-cli
            dockerfile: docker/docker/worker-cli/Dockerfile
            context: docker/docker/worker-cli
            component: worker-cli
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64
          push: true
          tags: |
            sunsolution/betterscan-${{ matrix.component }}:latest
            sunsolution/betterscan-${{ matrix.component }}:${{ github.sha }}
        
      - name: Anchore SBOM Action
        uses: anchore/sbom-action@v0.17.2     
