name: SPDX License Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spdx-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install

    - name: SPDX License Scanner
      uses: fossology/spdx-action@v2
      with:
        scan-folder: '.'  # Folder to scan, '.' scans the entire repo
        output-format: 'tag'  # Can be 'tag', 'rdf', or 'json'
        fail-on-error: true  # If true, the action will fail on license issues
